### ISSUE TITLE
interviews on feature-complete version

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#107]
Equality Explorer has been feature complete since 5/1/2018.   It's ready for formal interviews.  

To meet publication milestones, we need to start RC testing no later than 6/18.  Interviews need to be completed well before that date to allow for changes.

**Comment by pixelzoom** [comment]
Shooting for interviews on Fri 5/25/18.

**Comment by pixelzoom** [comment]
@amanda-phet said: shooting for interviews on Fri 5/25/18.

Interviews should include https://github.com/phetsims/equality-explorer/issues/80.

**Comment by amanda-phet** [comment]
Have two scheduled so far for next week, aiming for ~3 interviews. 

Still a question if we will include Basics and/or Systems spinoff sims, but I am hoping at the end of the interviews we can include them. It might also be worthwhile to interview on those separately, I'm not sure.

**Comment by pixelzoom** [comment]
Dev version for interviews:
https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.117/phet/equality-explorer_en_phet.html

**Comment by amanda-phet** [comment]
Today I'll be interviewing with the above version (dev.117) as well as the Two Variables sim (https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.116/phet/equality-explorer_en_phet.html). 

Hoping @pixelzoom will have a new version for interviews friday with the change discussed in https://github.com/phetsims/equality-explorer/issues/30#issuecomment-391113019.

**Comment by pixelzoom** [comment]
> Hoping @pixelzoom will have a new version for interviews friday with the change discussed in https://github.com/phetsims/equality-explorer/issues/30#issuecomment-391113019.

See https://github.com/phetsims/equality-explorer/issues/30#issuecomment-391126834.

**Comment by pixelzoom** [comment]
@amanda-phet requested "latest" dev versions, here they are:

[Equality Explorer 1.0.0-dev.119](https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.119/phet/equality-explorer_en_phet.html)

[Equality Explorer: Basics 1.0.0-dev.8](https://phet-dev.colorado.edu/html/equality-explorer-basics/1.0.0-dev.8/phet/equality-explorer-basics_en_phet.html)

[Equality Explorer: Two Variables 1.0.0-dev.1](https://phet-dev.colorado.edu/html/equality-explorer-two-variables/1.0.0-dev.1/phet/equality-explorer-two-variables_en_phet.html)

**Comment by amanda-phet** [comment]
3/4 interviews complete. Unfortunately, one family forgot, so I am really hoping we will be rescheduling that one for next week. 

Student (1): Plays on each screen except the Numbers screen. Notices the lock, but jumps to the Variables screen to use it. Clearly understands how the lock is supposed to work. Didn’t readily find the variable value control. When he gets to Operations, he finds the control, but clicks around the operators for a while before finally using the go button. Once he uses it, he understands how to use the UOC. Ended with Two Variables sim and realized it was essentially the same thing but with two variables instead of one. 

Student (2): Started with the Basics sim. Student tried to find some balanced scenarios, but on the Lab screen didn’t find the object value controls until prompted to use it. In the full sim, he likely noticed that the first screen was the same, and jumped ahead to play with the Numbers screen. Easily discovered that opposites cancel. Does not change the value of x on the Variables screen. Does not find the lock. Tries the game, and conceptually understands what a solution is, but doesn't have formal "solving" skills to apply in order to complete a challenge. he can’t “enter” an answer, and still doesn’t understand the universal operation. So the game is quite a challenge. 

Student (3): Started with the Basics sim, but with **snapshots minimized on startup.** Seems to enjoy playing with all of the various objects. When he gets to the Lab screen, he almost immediately notices that he can change the values! Follow with the full ExEx sim, and he immediately jumps to Operations. Notices the operation control but does not use the yellow button. However, he plays with the value of x and explores how the balance changes. He clicks the lock a bunch of times but doesn’t find that it does anything. Then he drags a term and notices that there are two terms. Gets excited to try the game screen. Uses the operand picker to "enter" his answer, but since he doesn't know how to use the UOC things get messy. Finally figures out what the control does, and eventually solves a challenge. From there, he works on more challenges. 

**Summary of my thoughts:** 
* I think we should keep the snapshots minimized by default for all sims. This seemed to help the last student find the pickers, and with one more interview to confirm I am hopeful that this will allow us to keep the variable pickers at the top of the sim. We also know that this is more of a teacher control, so I think having it minimized at startup is a good way to scaffold. 
* I am unsure about the UOC right now. Every student clicked the operation radio buttons expecting something to happen. I showed student (2) the old picker style and he seemed to think it wasn't much different. I forgot to show student (3) because he eventually found the yellow button, but wish I had shown him. 
* I think the lock feature is working and doesn't need any changes.

Leaving this issue open until the 4th interview is confirmed.

**Comment by pixelzoom** [comment]
Would you like the Snapshots accordion box minimized by default for the 4th interview?

The UOC is proving to have some usability problems.  Should we try interviews with the design (reverse Polish notation) that @ariel-phet proposed in https://github.com/phetsims/equality-explorer/issues/77#issuecomment-384853083?

**Comment by amanda-phet** [comment]
Interview (4) complete. Same grade level as (1) and (3). I had snapshots minimized on startup (I manually did this for all except the game screen) and it definitely helped with this student too, so I'm going to recommend that as a change for all screens. This student had no problems with the UOC and immediately began using it correctly. 

I think what could have caused issues with the UOC is that students at this age understand what a solution is, and on something like level 1 can identify the solution almost immediately, but don't have a formalized strategy for solving some students tried using the UOC to "enter" an answer. Since student (4) encountered the UOC on the Operations screen prior to seeing it in the game, and was using it correctly there, he wasn't confused with it in the game screen. I still believe it is an improvement over the picker control, because the student can easily identify the exact operation they want to apply. The issue might just be that students don't really understand why it is useful to "divide both sides by 2" yet. I think that a more purposeful guided exploration of the Operations screen will help students learn about inverse operations and thus know when and how to use inverse operations when solving.

**Comment by amanda-phet** [comment]
>The UOC is proving to have some usability problems. Should we try interviews with the design (reverse Polish notation) that @ariel-phet proposed in #77 (comment)? 

I am fine doing that, but I would need to schedule additional interviews and I won't be able to do that until at least next Thursday 6/7 because of next week's workshop. 

After the 4th interview, I am less concerned about usability issues. Can we discuss this in tomorrow's design meeting?

**Comment by pixelzoom** [comment]
Summary of Slack conversation with @amanda-phet:

(1) We will have a design meeting on Thursday 5/31 (tomorrow) to discuss the interview results.

(2) Change the Snapshots accordion box to be collapsed by default.

**Comment by amanda-phet** [comment]
Interviews complete.
