### ISSUE TITLE
How to cue when the balance is in "linked" mode

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/equality-explorer#11]
This sim has a linked mode, which when active, allows the user to add/remove objects from *both sides of the balance at the same time.* 

The current design of this sim uses an interactive train coupler to cue when the two sides are linked or unlinked. There are some issues with this design, namely that the actual balance doesn't get the same visual cue as the panels (other than a color change that breaks the intentions of the color cue). Another concern is that the couplers are very heavy-handed. 
![screen shot 2017-09-26 at 2 04 28 pm](https://user-images.githubusercontent.com/7852916/30881642-b6f01148-a2c3-11e7-87a4-885e32f85561.png)
![screen shot 2017-09-26 at 2 04 51 pm](https://user-images.githubusercontent.com/7852916/30881643-b706cece-a2c3-11e7-82f9-a53b6b5a4cc3.png)

@pixelzoom has published a few dev versions with variants of the coupler:
[dev.19](http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.19/equality-explorer_en.html) 
![screen shot 2017-09-26 at 2 07 44 pm](https://user-images.githubusercontent.com/7852916/30881758-1996cf30-a2c4-11e7-94b7-62f2d9822e2a.png)

[dev.20](http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.20/equality-explorer_en.html)
![screen shot 2017-09-26 at 2 08 46 pm](https://user-images.githubusercontent.com/7852916/30881801-3d11fd9a-a2c4-11e7-9464-4d4b9e626590.png)

[dev.21](http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.21/equality-explorer_en.html)
![screen shot 2017-09-26 at 2 09 01 pm](https://user-images.githubusercontent.com/7852916/30881815-4b1d6de8-a2c4-11e7-94a5-80f3d2cf6d61.png)

Other ideas worth considering:
(1) A visual cue on the balance and/or the equation display, such as a padlock, when the balance is locked
![screen shot 2017-09-26 at 2 10 00 pm](https://user-images.githubusercontent.com/7852916/30881863-693ecf38-a2c4-11e7-9225-081a55b2a03f.png)

(2) Using a toggle or button with chain link icons instead of a coupler 
![screen shot 2017-09-26 at 2 11 26 pm](https://user-images.githubusercontent.com/7852916/30881921-9f698940-a2c4-11e7-821d-ebc592bbbfa2.png)

(3) Conducting some early interviews to see if students need the color-coded cueing of red and blue to distinguish the right and left sides of the balance (because that would remove some visual distraction from a padlock appearing)

(4) Perhaps a continuation of (3) above... making the panels much closer to the plates so a color cue is not needed, such as a "drawer" similar to what is in function builder (this is an extremely rough mockup)
![screen shot 2017-09-26 at 2 20 21 pm](https://user-images.githubusercontent.com/7852916/30882350-dfe028ac-a2c5-11e7-9a09-7a70df5f2a3f.png)

(5) Another idea for a general cue is that we could have a hover glow on objects before clicking them (not sure how this would work on touch), and if linked, the hover would appear on an object on both sides (if applicable). This idea needs more fleshing out, and the touch issue might be enough to make it not worth pursuing.

**Comment by pixelzoom** [comment]
The radio-button approach in (2) above is demonstrated in http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.18/equality-explorer_en.html

**Comment by pixelzoom** [comment]
Some of my comments that didn't get transferred from the Slack thread:
• With the "train couplers" in the design doc, it's odd that the coupling is associated with the panels, since it’s not solely the panels that are coupled.  If you take something off the scale, that doesn’t involve the panels at all.
• What the coupling _is_ associated with is the scale. When coupled, the angle of the scale will not change. Any changes to items will be applied to both plates, so that the scale remains at its current position.
• The design doc shows that the colors of the couplers, plates and panels all "grey out" when coupled. I'm not convinced that this is good feedback.  It seems to imply that you can now (for example) drag something from the left panel to the right plate.   I get it that you want something that indicates "a change", but I don't think this color change is it.

That said...

Here's another take on idea (1) above, the padlock on the scale.  See [1.0.0-dev.22](http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.22/equality-explorer_en.html).  I'm currently using the fontawesome icons for lock and unlock, but image a super-inviting icon that just begs the user to click on it :)    The icon is positioned above the arrow that indicates the scale's angle, because it's the scale angle that's locked.

![screenshot_396](https://user-images.githubusercontent.com/3046552/30883828-af22d6a6-a2ca-11e7-8e64-755d09fd8412.png)

**Comment by pixelzoom** [comment]
Maybe it would help to clarify this if we stopped using terms like "coupled" and "linked".  When items are added to the scale, the balance beam's angle typically changes (unless the scale is "bottomed out").  What we're doing is locking the balance beam, so that it can't move.  When the balance beam is locked, if you change the weight on one side of the scale, the weight on the other side of the scale must automatically change by the same amount.

**Comment by pixelzoom** [comment]
9/27/17 design meeting:
• Remove color coding from plates and panels.
• Try the padlock shown in approach (1) above, but place the padlock between the 2 panels.  @amanda-phet will provide @pixelzoom with the artwork.

**Comment by pixelzoom** [comment]
All of the decisions in https://github.com/phetsims/equality-explorer/issues/11#issuecomment-332652682 have been implemented in [1.0.0-dev.24](http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.24/equality-explorer_en.html).  I realize that we won't be able to properly evaluate whether there's enough feedback until the "coupling" feature has been implemented and interviewed. 

@amanda-phet Do you want to leave this issue open until after interviews ? Or close this issue and create a new issue if/when we need to make further changes?

**Comment by amanda-phet** [comment]
Since this issue was opened to address the design, and we've come up with a decision, I'll open a new one if interviews expose issues with the linked functionality (or reopen this one if we want to change the design).

**Comment by amanda-phet** [comment]
Also, I'm really happy with the appearance at the moment.. the balance looks much cleaner (which was the hope with the simple design) and the lock seems to stand out to me in a good way. Seeing it start in an unlocked state makes me think it can be locked. 

I am very interested to see what students thing.. if they find it and click on it, and if they understand what it does!

**Comment by amanda-phet** [comment]
Idea that we may want to consider: when the user clicks "lock", a simple lock appears ON the balance for some immediate feedback.
