### ISSUE TITLE
range of pickers on Lab screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#121]
The range of the pickers on the Lab screen is currently [0,20].   Zero has potential for confusion, since the objects here are physical.  Do we want to change to [1,20]?

**Comment by pixelzoom** [comment]
Note to self... Code to change is in LabScene:

```js
27   var VALUE_RANGE = new Range( 0, 20 );
```

**Comment by pixelzoom** [comment]
5/31/18 design meeting:  @kathy-phet feels that the min should be 1, because of the connection to physical objects and the audience.  @ariel-phet was OK with min of zero.  We tabled the discussion and @amanda-phet will decide.

**Comment by pixelzoom** [comment]
@amanda-phet Dev testing on this sim will start on Monday 6/18.  Since this involves a code change, it would be good to wrap this issue up before then.

**Comment by kathy-phet** [comment]
I still prefer sticking with the concrete representation here and starting at 1 for this sim.

K

Sent from my iPhone

On Jun 14, 2018, at 11:33 AM, Chris Malley <notifications@github.com<mailto:notifications@github.com>> wrote:


@amanda-phet<https://github.com/amanda-phet> Dev testing on this sim will start on Monday 6/18. Since this involves a code change, it would be good to wrap this issue up before then.

**Comment by amanda-phet** [comment]
I agree with @kathy-phet .

@pixelzoom please change the range to [1,20].

**Comment by pixelzoom** [comment]
Range has been changed to [1,20]. Closing.
