### ISSUE TITLE
bounce when term lands on term

### ISSUE THREAD

**Issue by ghost** [phetsims/equality-explorer#132]
For phetsims/QA/issues/131. Noticed while testing EqEx: Two Variables on macOS + FF.

Here's what it looks like when a term lands on top of another term:

![eqex](https://user-images.githubusercontent.com/31285590/41993361-7af47d6a-7a08-11e8-82fb-82dc390261df.gif)

And here's what it looks like when a term lands on the scale:

![eqex1](https://user-images.githubusercontent.com/31285590/41993386-8b16e80e-7a08-11e8-9d3a-2fbbabc6c344.gif)

Is the bounce intended?

**Comment by amanda-phet** [comment]
>Is the bounce intended?

No, that is not part of the design. I only see it on the left of the first gif and right of the second gif. Is that accurate? Or are you seeing it everywhere?

**Comment by ghost** [comment]
> I only see it on the left of the first gif and right of the second gif. Is that accurate?

@amanda-phet, I hadn't noticed the slight bounce on the right of the second gif. Thanks for pointing that out.

Originally, I thought the bounce only occurred when a term landed on top of another term, but apparently this is not the case.

The intention of using the two gifs was to juxtapose the bouncing behavior that can be observed in the first gif on the left with the "smooth landing" behavior that can be observed in the second gif on the left.

I just looked at the sim, and the bounce is only noticeable when one terms lands on top of another. I think the bounce that can be observed in the second gif on the right is too small to notice "in action."

**Comment by pixelzoom** [comment]
While the lock is on, the _equivalent_ term tracks the _dragged_ term.   When the dragged term reaches its target cell on the plate (either via dragging or animating), the equivalent term jumps to a cell on the opposite plate.  This jump is the "bounce" that you're seeing.   

The alternative involves animating terms at proportional speeds, and we decided long ago not to do that, due to complexity and multi-touch.  We can revisit, but it will be costly.

@amanda-phet please advise on how to proceed.  If the current behavior is still acceptable, please close this issue.

**Comment by amanda-phet** [comment]
>When the dragged term reaches its target cell on the plate (either via dragging or animating), the equivalent term jumps to a cell on the opposite plate. This jump is the "bounce" that you're seeing.

I was wondering if that's what was causing the issue, actually. I am fine with this behavior since it is consistent with the rules we defined. It's also fairly minor to my eye.
