### ISSUE TITLE
create auxiliary screenshots 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#147]
From the master checklist in #1:

> - [ ] Auxiliary screenshots (up to 3 additional)

**Comment by phet-steele** [comment]
@KatieWoe please take these screenshots and follow the naming scheme from other sims:


The first is one @KatieWoe had in #125 that I thought could be used for an alternate:

![image](https://user-images.githubusercontent.com/5863899/48163845-04521b00-e29e-11e8-8f5e-34eb9024ba02.png)
![image](https://user-images.githubusercontent.com/5863899/48165349-85abac80-e2a2-11e8-8b7d-6b7c557a1d8d.png)

For this last one, you don't have to get this exactly since the equation is not that important. What is important is: Level 2, 3 solved already, one step done, spinner NOT showing last step but stays on what you just did for first step.

![image](https://user-images.githubusercontent.com/5863899/48165833-18991680-e2a4-11e8-97a2-7cac3e1813aa.png)

**Comment by amanda-phet** [comment]
One request- a different value for x in the first one. Since 1 is the
default it is nice to show that x can be something like 20.

**Comment by KatieWoe** [comment]
Since some changes were requested I'm posting the screenshots here for final review before committing them.  @amanda-phet 
![equality-explorer-screenshot-alt1](https://user-images.githubusercontent.com/41024075/48210797-4d08e300-e335-11e8-9d2d-dd7254989b53.png)
![equality-explorer-screenshot-alt2](https://user-images.githubusercontent.com/41024075/48210798-4da17980-e335-11e8-959f-ca3f7cbdf4ed.png)
![equality-explorer-screenshot-alt3](https://user-images.githubusercontent.com/41024075/48210800-4da17980-e335-11e8-888f-3faf22cc9380.png)

**Comment by amanda-phet** [comment]
Now that the operations screen is more unbalanced, I have one more request. Can you make the Basics screen a little less unbalanced, and leaning to the right? Just for some more visual interest, so that all 4 together have two balanced, one unbalanced to the left, and one unbalanced to the right. Thanks!

**Comment by KatieWoe** [comment]
@amanda-phet 
![equality-explorer-screenshot-alt2](https://user-images.githubusercontent.com/41024075/48213718-ad028800-e33b-11e8-983c-ade6eec3959b.png)

**Comment by amanda-phet** [comment]
Looks good. Thanks!

**Comment by KatieWoe** [comment]
This should be done
