### ISSUE TITLE
add a control to show/hide '1' coefficients

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#16]
In https://github.com/phetsims/equality-explorer/issues/6, @kathy-phet asked an unrelated question. I'm deleting it from that issue and moving it here.

> Also - Amanda, in playing I noticed equation lists the "1"? Did we discuss that? Should it be optional?

**Comment by pixelzoom** [comment]
FYI... The current requirement is to hide the '1' coefficient for variable ('x') terms and show them for terms in the Basics screen. I can certainly change that, but wanted you to know that it didn't happen by accident.

**Comment by kathy-phet** [comment]
Thanks for starting a new issue - and for the info. Yes, I figured it wasn't an accident. I think its nice to have it there, but also wondering if should be optional to toggle as we do in other sims.

**Comment by pixelzoom** [comment]
> wondering if should be optional to toggle as we do in other sims.

Are you suggesting a check box? query parameter?

**Comment by kathy-phet** [comment]
I'm thinking about expression exchange. There it is a checkbox. But let's just say, I am suggesting a discussion item.

**Comment by pixelzoom** [comment]
My first concern would be whether such a control is really necessary in this sim.  The UI is already relatively cluttered, so we should think carefully about adding anything else.

If we do want to add a check box... Our options for where to locate additional controls are limited. This control should be located in close proximity to the equation accordion box, but there's no space for it.  The only available space is to the right of the "Reset All" button. 

Expression Exchange also adds a '1' before each item in the bottom panels.  At this point in development, doing that in Equality Explorer would be a major ordeal - and imo unnecessary.

**Comment by pixelzoom** [comment]
Labeling as high priority.  This affects so many things that I need to know immediately if you want this feature.

**Comment by amanda-phet** [comment]
I don't think it is necessary to add a control for coefficients. Here are some of my thoughts about the current implementation: 

* In ExEx, it was a major part of the learning goals, because you could combine coins to create "stacks" that were only indicated as such by a coefficient, so it is natural to want to see a coefficient of 1 to be consistent, or turn it off if you already understand the concept. 
* On the Basics screen, I think coefficients of 1 are useful because they adds structure to the equality statement and make the pictures look more symbolic. Without 1s, the pictures just seem odd to have in an equation. (cat + dog = turtle seems nonsensical, but 1cat + 1dog = 1turtle makes the animal icons seem like representations of an unknown quantity.) Perhaps this is just me, though. 
* On the Variables and Solving screens, I think it's important to *not* show coefficients of 1 because we want that equality statement to look as close to a typical abstract equation as possible. It is clear in the balance representation if there is 1 x sitting on a plate, and reinforces what a single "x" in an equation means.

**Comment by pixelzoom** [comment]
@amanda-phet said:
> • Without 1s, the pictures just seem odd to have in an equation. (cat + dog = turtle seems nonsensical, but 1cat + 1dog = 1turtle makes the animal icons seem like representations of an unknown quantity.) Perhaps this is just me, though.

It's not just you, I agree :)

@kathy-phet Are you OK with decision not to add this feature?  If not, please discuss with @amanda-phet at your earliest convenience.

**Comment by pixelzoom** [comment]
@kathy-phet still waiting for your reply.

**Comment by pixelzoom** [comment]
As noted 6 days ago in https://github.com/phetsims/equality-explorer/issues/16#issuecomment-337674354:
> Labeling as high priority. This affects so many things that I need to know immediately if you want this feature.

To be clear... I'm not proceeding with some development until this issue is resolved. And I'm waiting for response from @kathy-phet.

**Comment by kathy-phet** [comment]
I'm OK leaving as is. Thanks for discussing it.
