### ISSUE TITLE
Equality Explorer - Publish 1.1 with game enhancements

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/equality-explorer#167]
_@pixelzoom edit, because this comment was empty._

The goal is to publish these 2 enhancements:

* #164 
* #165

**Comment by pixelzoom** [comment]
With the exception of #164 and #165, there have been no significant changes to this sim since 1.0 was published, so I don't expect any sim-specific problems.  On the other hand, the 1.0 branch was created in July 2018, more than 3 years ago. It predates the switch to ES6, and there have probably been thousands of significant common-code changes since then.  If we do have any problems, it's most like to be something that snuck into common code.  That said...

How would you like to proceed with QA?  Full dev or dev-lite? Full RC or RC-lite?

**Comment by pixelzoom** [comment]
With the exception of #164 and #165, there have been no significant changes to this sim since 1.0 was published, so I don't expect any sim-specific problems.  On the other hand, the 1.0 branch was created in July 2018, more than 3 years ago. It predates the switch to ES6, and there have probably been thousands of significant common-code changes since then.  If we do have any problems, it's most like to be something that snuck into common code.  That said...

@kathy-phet @amanda-phet How would you like to proceed with QA?  Full dev or dev-lite? Full RC or RC-lite?

**Comment by kathy-phet** [comment]
@pixelzoom - My recommendation would be a dev-lite just to check it out reasonably quickly, followed by a full rc.

**Comment by pixelzoom** [comment]
In Slack, @amanda-phet said:
> Thanks Kathy, your recommendation makes sense to me

**Comment by pixelzoom** [comment]
11/3/21 dev version published for dev-lite testing:

* https://github.com/phetsims/qa/issues/732

EDIT: test completed on 11/5/21

**Comment by pixelzoom** [comment]
11/9/21:  1.1 release branch created, RC test created:

* https://github.com/phetsims/qa/issues/735

EDIT: 11/19/21 test completed. Another RC spot-check will be needed.

**Comment by pixelzoom** [comment]
11/19/21: RC test created:

* https://github.com/phetsims/qa/issues/743

EDIT: 11/22/21 test completed, ready to publish.

**Comment by pixelzoom** [comment]
1.1.0 published to https://phet.colorado.edu/en/simulations/equality-explorer.   Closing.
