### ISSUE TITLE
Inverse terms do not cancel when scale is full and lock is on.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#173]
For phetsims/qa#732.

In https://github.com/phetsims/equality-explorer/issues/171#issuecomment-963579116, @KatieWoe reported that inverse terms do not cancel when the scale is full.  See the example below.  If there was an empty space on the right scale, then cancellation would occur on the left side, and -x would be put in the empty space on the right side.  There is no requirement that x and -x should cancel on both sides.

Based on the specification in https://github.com/phetsims/equality-explorer/blob/master/doc/lock-scenarios.md, this is currently not a supported scenarios. Because of how complicated the lock feature is, adding support for this will be difficult, expensive, and potentially destabilizing.

@amanda-phet  how would you like to proceed for the 1.1 release?  And for future releases?

![wontcancel](https://user-images.githubusercontent.com/41024075/140819022-8c5dbafc-256b-4459-b8b3-b853f528bbd7.gif)

**Comment by amanda-phet** [comment]
Since both sides of the balance are full, I don't find this scenario to be extremely confusing. Trying to add another term to both sides doesn't make a ton of sense to me if both sides are full. And the user *can* still remove an x from both sides if they want. My recommendation is to leave this as it is and not support this edge case in this release or in any future release, since there isn't really a bug.
