### ISSUE TITLE
Should "Next" button in game screen show up faster?

### ISSUE THREAD

**Issue by stemilymill** [phetsims/equality-explorer#180]
For https://github.com/phetsims/qa/issues/735.

While testing the Solve It! screen, it always seemed like the "Next" button should come up more quickly (and maybe the smiley face too); it felt like the time in between questions interrupted game flow a bit.

**Comment by pixelzoom** [comment]
The delays that you are perceiving are not in fact delays.  There is a necessary sequence here, due to the (requested) animatons that run before the operation is applied, and before we can proceed to the next challenge.

When you push the "apply operation" button (yellow button with ↴ symbol), the operation is not immediately applied. An animation of the operation begins, showing the operation falling toward the scale, on both sides of the scale. The operation is applied when the operation reaches the scales. The smiley face then appears immeditely; there is no delay.

When the smiley face appears, another animation begins, to fade out the smiley face. Until the smiley face disappears, it overlaps the space where the Next button appears.  As soon as the smiley face is gone, the Next button is made visible immeditely; there is no delay.  

The duration of these animations is flexible. But durations were tuned during the design and implementation of the sim, and they still seem good to me.  We could shorten one or both animations if we want to decrease the time between pushing the "apply operation" button and making the "Next" button visible.

@amanda-phet would you like to change anything here?

**Comment by amanda-phet** [comment]
@pixelzoom is correct that a challenge isn't correct/incorrect until the operation has been fully applied, so I do want that animation to finish and see "x = 5" before it can be marked correct/incorrect. My guess is that since we are not the ones learning this content, we are more annoyed by the extra time, but a kid just learning this might benefit from the current pace.
