### ISSUE TITLE
Move LockControl to scenery-phet

### ISSUE THREAD

**Issue by zepumph** [phetsims/equality-explorer#182]
In https://github.com/phetsims/ratio-and-proportion/issues/414 it was requested to have these two toggle-able icons be a part of the ratio-lock checkbox. I'm thinking that we move this to common code, and add an option called `interactive` which adds the FireListener, but otherwise the provided Property just changes the icon. 

@pixelzoom you are the responsible dev, does that seem reasonable to you?

**Comment by terracoda** [comment]
@zepumph, we should discuss today because if the actual checkbox is not visually present, the lock on it's own is likely better as a toggle button rather than a checkbox.

If the checkbox is visually present, and the lock is part of the label the lock itself is not the interaction, the interaction is an HTML checkbox. If only the lock is visually present, it is playing double duty as a label and an interaction, and in that case it would be better as an HTML toggle button.

**Comment by pixelzoom** [comment]
As described, moving LockControl to common code doesn't seem like the right approach.  It would be better to have a LockNode whose visual changes based on a BooleanProperty `lockedProperty`. Then reuse that in LockControl and your checkbox.  If you'd like me to take the lead on that, let me know.

In the case that @terracoda mentioned (where the checkbox is hidden), I don't know you want to address that.  The checkbox can presumably be hidden via PhET-iO, and I don't think you want to dynamicaly change the role of the UI component.  It would be best to address this while considering the general issue of how to implement a "display only" feature for UI components (sorry, I can't find the relevant GitHub issue.)

**Comment by terracoda** [comment]
Just to be clear, I didn't suggest changing the role of an element in a simulation.

**Comment by zepumph** [comment]
@terracoda and I met, and we agree with @pixelzoom. Do you mind moving just the `LockNode` to common code for us?

**Comment by pixelzoom** [comment]
Will do!  I might get to it later today Fri 12/3, but can definitely get it done by end of day Mon 12/6.

**Comment by zepumph** [comment]
I won't act on this until perhaps 12/10, so take your time!

**Comment by pixelzoom** [comment]
In the above commits, I factored out `LockNode`, and migrated it (along with images and asset) to scenery-phet.   Note that it's a .js file, not .ts, because TS didn't recognize `Image` as a subtype of `Node`, and was therefore giving me grief about the arguments to `super`.  I also didn't want to spend time on `options` because I'm not clear on the recommend TS pattern.

@zepumph please review.

**Comment by zepumph** [comment]
Looks really good. Thanks for the quick turn around.

**Comment by pixelzoom** [comment]
Happy to help. Closing.
