### ISSUE TITLE
Equivalent term isn't interactive on Operations Screen

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/equality-explorer#218]
**Test device**
MacBook Air M1 chip + iPad

**Operating System**
15.0.1 + iPad18

**Browser**
Safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1172 on the Operations Screen, with the lock on, I can only interact with the original term I put on a plate. The equivalent term on the opposite plate isn't draggable. This is different than in published.

**Steps to reproduce**
1. On the Operations Screen, turn on the lock
2. Put an x on the left plate
3. Try to grab the equivalent x on the right plate
4. Put a 1 on the right plate
5. Try to grab the equivalent 1 on the left plate

**Visuals**

https://github.com/user-attachments/assets/5773f9ef-e175-4bee-a3f1-169d90f6ffbf

**Comment by Nancy-Salpepi** [comment]
This also occurs if adding terms using the operations. 

Steps:
1. Turn the lock on
2. Use the operations so that each plate contains `2x-3`
3. Grab the 2x on the left side and then release, so it returns to the plate
4. Try to grab the 2x on the right side
5. Grab the 3 on the right side and then release, so it returns to the plate
6. Try to grab the 3 on the left side

**Comment by Nancy-Salpepi** [comment]
If I turn the lock off after completing the steps in earlier comments, the term that wasn't interactive, still isn't interactive.

**Comment by pixelzoom** [comment]
Reproduced in main. It's only a problem on the _Operations_ screen.  It doesn't matter which plate or whether the term is _x_ or 1.

I suspect that this is related to Term `pickableProperty`.  It's probably not being set to true when the drag ends.

**Comment by pixelzoom** [comment]
I've tracked this down to CombineTermsDragListener, which is the drag listener used for the Operation screen.  It seems like we should be hitting `this.equivalentTerm.pickableProperty.value = true` on line 294.  But we're never getting there because this is being done on line 246:

```ts
            !this.equivalentTerm.isDisposed && this.equivalentTerm.dispose();
            this.equivalentTerm = null;
```

I was able to revert CombineTermsDragListener.ts back to 3285c43 on 9/22/22, which has commit message "rename .js to .ts".  The problem is still present there, so it seems that the regression was introduced before conversion to TypeScript.  Or the regression is elsewhere.

**Comment by pixelzoom** [comment]
This change in CombineTermsDragListener fixes the problem.  But I need to investigate what changed to make it necessary.

```diff
            const equivalentTermCopy = this.equivalentTerm.copy( {
+             pickable: true,
              diameter: EqualityExplorerConstants.BIG_TERM_DIAMETER
            } );
```

**Comment by pixelzoom** [comment]
> ...  But I need to investigate what changed to make it necessary.

It is necessary because of a change to Term `copyOptions` in https://github.com/phetsims/equality-explorer/commit/e6b4a5000326d0f29f754756a3e116dd4ed27eaf for https://github.com/phetsims/equality-explorer/issues/199 on 10/31/2022.  `pickable` was not previously included in a copy of a Term.  Now that it is included, the copy ends up being `pickable: false`. So we must explicity set it to `pickable: true` as shown in https://github.com/phetsims/equality-explorer/issues/218#issuecomment-2486838636.  And there are actually 2 occurrences of `equivalentTerm.copy` to be addressed.

**Comment by pixelzoom** [comment]
@Nancy-Salpepi great find on this one. Please review in main, close if OK.

**Comment by Nancy-Salpepi** [comment]
Working great in main!
Closing.
