### ISSUE TITLE
refine UX for snapshots feature

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#23]
With the exception of the "restore" button, the Snapshots feature is fully functional in [1.0.0-dev.43](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.43/equality-explorer_en.html).  

@amanda-phet please review and let me know what changes you'd like to make to the UX.

**Comment by pixelzoom** [comment]
A few notes about the implementation in 1.0.0-dev.43:

• font size is 28, identical to "Equation or Inequality" accordion box (can be customized)
• spacing between parts of the equation is identical to "Equation or Inequality" accordion box (can be customized)
• equations are scaled down to fit the width of the accordion box
• spacing between equation and "(x = 2)" is 10
• selected snapshot is outlined with `lineWidth:2`, `stroke:'red'`, `cornerRadius:10`
• clicking outside the Snapshots accordion box will clear the selected snapshot
• margin on the accordion box is `contentXMargin:10`, `contentYMargin:10`

**Comment by amanda-phet** [comment]
* I think the spacing between parts of the equation in the snapshots should be modified a bit. The current equality symbol is much larger than the surrounding text, and in the snapshot that isn't necessary. Can you scale the equality symbol down to match the weight and size of the rest of the snapshot text? 
* The snapshot outline needs a little more spacing to the left and right of the equation within the red outline. You can see here that it's pretty tight, and since there is a nice margin I think there is room to make the outline wider. 
<img width="302" alt="screen shot 2017-12-06 at 9 59 15 am" src="https://user-images.githubusercontent.com/7852916/33674384-8f1866bc-da6c-11e7-8d12-0cd272776511.png">

* The mockup of the snapshot outline had a gray stroke (#808080) and no rounded corner (to distinguish it from the outer panel). Did you try this and decide it didn't look good?
<img width="353" alt="screen shot 2017-12-06 at 10 00 15 am" src="https://user-images.githubusercontent.com/7852916/33674346-75e8f01c-da6c-11e7-96fa-2c8b09c98085.png">


The scaling looks like it is working well and I'm happy with the appearance. I also like the appearance of the variable value in parentheses "(x = 2)".

**Comment by pixelzoom** [comment]
@amanda-phet said:
> I think the spacing between parts of the equation in the snapshots should be modified a bit.

Spacing is currently identical to the equation in the "Equations and Inequalities" accordion box.  Here are the spacing options, please provide specifics on what you'd like to change:

```js
      // horizontal spacing
      relationalOperatorSpacing: 20, // space around the relational operator
      plusSpacing: 8, // space around plus operator
      coefficientSpacing: 2 // space between coefficient and icon
```

> The current equality symbol is much larger than the surrounding text, and in the snapshot that isn't necessary. Can you scale the equality symbol down to match the weight and size of the rest of the snapshot text?

You mean the relational operator? Will do.

> The snapshot outline needs a little more spacing to the left and right of the equation  ...

Will do.

> The mockup of the snapshot outline had a gray stroke (#808080) and no rounded corner (to distinguish it from the outer panel). Did you try this and decide it didn't look good?

No -- but the mockups are so out of date that I wasn't certain about which parts of the mockups are requirements, stale, etc.  And since these are functioning as radio buttons (ala scene selection) I was trying to match the look of common-code radio buttons.  (Unfortunately I can't use common-code radio buttons here since they require exactly 1 thing to be selected, and we need 0 or 1 selection.)   I'll switch to gray stroke and square corners.

**Comment by pixelzoom** [comment]
In [1.0.0-dev.44](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.44/equality-explorer_en.html):

• deemphasized the relational operator
• change selection rectangle (`cornerRadius:0, stroke:'rgb( 128, 128, 128 )'`)
• added margin inside selection rectangle

I'm not wild about the `cornerRadius:0` (square corners), it's inconsistent with PhET radio buttons and subtly severe.  Compare:

`cornerRadius:0` -

![screenshot_01](https://user-images.githubusercontent.com/3046552/33676922-4db1c800-da74-11e7-8b87-cd0ffd5f2a28.png)

`cornerRadius:3` -

![screenshot_93](https://user-images.githubusercontent.com/3046552/33676931-56c0e84a-da74-11e7-85e6-69633c752968.png)

**Comment by pixelzoom** [comment]
@amanda-phet here's what's left to do:

• Specify how you want the horizontal spacing adjusted. See https://github.com/phetsims/equality-explorer/issues/23#issuecomment-349711478.

• Decide whether a small cornerRadius is OK, or whether you really want square corners on the selection rectangle.

**Comment by amanda-phet** [comment]
* I don't think I meant the spacing, just the relational operator. Sorry about that. I must've started one thought and finished with another. The spacing looks good to me. 

* I think you're right that the square corners don't work here. I also think a color might work for the stroke if it could also match the "reload" button color. The reload button becoming active is pretty subtle in a colorful screen. The red stroke is so bold that it seems to make the button situation even worse. So maybe we need a bold stroke and button, to make the connection really obvious (especially since the button is far from the top snapshots). And, the yellow snapshot buttons should probably be white instead of yellow, to tone them down. What do you think of this rough mockup using blue as an example?
<img width="234" alt="screen shot 2017-12-06 at 11 52 31 am" src="https://user-images.githubusercontent.com/7852916/33679470-1400f70e-da7c-11e7-810d-0d8b30377e27.png">

**Comment by pixelzoom** [comment]
Requests in https://github.com/phetsims/equality-explorer/issues/23#issuecomment-349738365 are incorporated in [1.0.0-dev.45](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.45/equality-explorer_en.html), including:

• use 'white' for color of snapshot buttons
• use 'rgb( 85, 169, 223 )' for color of reload button and selection rectangle
• lineWidth:3 (was 2) for selection rectangle
• cornerRadius:3 (was 0) for selection rectangle

Seems reasonable to me. @amanda-phet back to you.

**Comment by amanda-phet** [comment]
I am really happy with the blue outline and button (but am certainly open to other color choices). I think we should stop tweaking UX at this point and wait to see what happens in interviews. 

The one thing I have an open question about is whether to decrease the font size of *all* of the snapshots, not just the extra long ones. We've discussed this in the past so I'm happy moving forward with our current decision, but in the back of my mind I'm still wondering if we should make them all the smallest size for consistency. (I looked on an iPad and thought it looked very readable.) 

Should I go ahead and close this issue?

**Comment by pixelzoom** [comment]
@amanda-phet said:
> The one thing I have an open question about is whether to decrease the font size of all of the snapshots, not just the extra long ones.

This is relatively simple for me to try out.  Would you like to see a dev version?

If we do make the font size consistent, then another thing to consider is whether to horizontally align the relational operator of all snapshots.  (I may already have support for that, but would need to confirm.)

**Comment by pixelzoom** [comment]
More thoughts about https://github.com/phetsims/equality-explorer/issues/23#issuecomment-350107481....

Making the font size uniform on the Basics screen might not be a good idea - it means that all of the equations will be very tiny (and they get pretty tiny).   We could investigate uniform font size on screens 2,3,4 only, but that would be a little more involved.

Aligning the relational operators will be a bit challenging for the screens that have the "show x" check box.

That said... I could still show you how uniform font size and relational operator alignment would look, then deal with the fallout later :)

**Comment by amanda-phet** [comment]
>Making the font size uniform on the Basics screen might not be a good idea - it means that all of the equations will be very tiny

Right, that's why I hesitate. But on screens 2-4 they don't get quite as tiny. What we could do, instead of a special case for those screens, is just have a smaller "maximum" size on all 4 screens. Then there is less variability overall. Thoughts? 

I don't think we should align the relational operators.

**Comment by pixelzoom** [comment]
@amanda-phet said:
> What we could do, instead of a special case for those screens, is just have a smaller "maximum" size on all 4 screens.

@amanda-phet please take a look at [1.0.0-dev.45](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.46/equality-explorer_en.html), where I've reduced the Snapshots font size from 28 to 20 for all 4 screens.  It looks much more harmonious to me.  

Use this URL if you want to initialize with "worst case" scenarios:
https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.46/equality-explorer_en.html?leftBasics=10,11,12&rightBasics=12,11,10&leftNumbers=10,0&rightNumbers=0,10&leftVariables=0,20,0,10&rightVariables=10,0,20,0

Be sure to set 'x' to something like -24 (2 digits and negative sign).

> I don't think we should align the relational operators.

Great, that makes my day :)

**Comment by amanda-phet** [comment]
This look more harmonious to me, too! I think it was a good change. On the one hand, we want things to be large and easy to read, but in these cases where the length of the equation can change, there is a must less drastic change in text size. I think it looks great. 

![screen shot 2017-12-08 at 11 10 09 am](https://user-images.githubusercontent.com/7852916/33779055-994efee6-dc08-11e7-93b8-8b2b6075bc5a.png)
![screen shot 2017-12-08 at 11 10 15 am](https://user-images.githubusercontent.com/7852916/33779059-9e260a72-dc08-11e7-8943-ec10279c5b01.png)

**Comment by pixelzoom** [comment]
Excellent.  We'll undoubtedly do more pixel polishing, but I think we can now close this issue.  Closing.
