### ISSUE TITLE
features for PhET-iO

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#31]
From the master checklist in https://github.com/phetsims/equality-explorer/issues/1:

> - [ ] Features for PhET-iO discussion

My understanding is that we're ignoring PhET-iO for this sim, and will instrument the sim at a later (post-publication) date.  Since there are no guidelines about what to do (or what not to do) to make a sim easy to instrument, I may (or may not) be making implementation decisions that impact instrumentation.

@ariel-phet If my understanding is correct, please acknowledge and close.  If not, then let's begin a (rather late) discussion of PhET-iO features for this sim.

Mentioning @amanda-phet and @samreid, so that they're in the loop.

**Comment by ariel-phet** [comment]
@pixelzoom your understanding for this sim is correct. I think after Faraday's law iO work is complete we will have a better idea and can work on such guidelines.

Closing.

**Comment by pixelzoom** [comment]
Thanks. I'll mark this item as addressed in the master checklist.

**Comment by samreid** [comment]
I don't know what the schedule is for this simulation or what the long term plan for PhET-iO instrumentation is.  But it seems it would save the most time in the long run to have a PhET-iO Design meeting early on (while the simulation is being designed and/or developed).  This way the primary developer will be able to account for the features in the main architecture of the simulation rather than have to try to retrofit them afterwards.  

Even if we don't proceed with full PhET-iO instrumentation now, knowing and accounting for the major PhET-iO features or customizable parts would be best during initial development.

Of course, if this sim is facing an imminent deadline, we would not be able to make this kind of long-term optimization.  Reassigned to @ariel-phet for discussion.

**Comment by samreid** [comment]
We discussed in slack, and @ariel-phet pointed out that deadlines for this sim as well as uncertainty about PhET-iO design and instrumentation strategy indicate we should postpone PhET-iO design for this sim at the moment.  I'll leave this open and assigned to @ariel-phet in case he wants to capture any more of the slack conversation here.
