### ISSUE TITLE
informal interviews

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#32]
@amanda-phet is planning to do informal interviews on Monday 1/8/18.  She has two 7th-graders scheduled.  One interview on desktop, one on iPad. 

The dev version for those interviews is [1.0.0-dev.55](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.55/equality-explorer_en.html).  The "lock" feature and "Solving" screen are hidden.

**Comment by amanda-phet** [comment]
I interviewed two 7th graders on Monday, both using an iPad (it was already set up, and I thought that would be more valuable for assessing #27 and #29)

First student:
- seemed really motivated to want to balance the two sides, but often put the same items on both sides in order to do this
- 11 minutes in to the interview he was "done" so I asked some questions to gain more insight into use (especially since he hadn't used the snapshots or tried to find the values for the the objects on the Basics screen)
- when prompted to find out the values of the objects, he used a strategy of assigning 1 to the apple and using that to find the values for the orange and lemon. 
- when asked about the snapshots, he used it to "take a picture" and quickly realized he could also reload them
- when asked about dragging objects from one side to the other (because I noticed he tried this) he did not seem bothered and even said that objects on each side of the equation are separate. 

Second interview:
- use snapshot on his own and learned how to use it quickly
- used snapshots to save equality statements when trying to figure out the values of the objects on the Basics screen
- noticed both the arrow and equality statement when he was trying to balance, but usually looked at the equality statement

**Comment by pixelzoom** [comment]
@amanda-phet said:
> I interviewed two 7th graders on Monday, both using an iPad (it was already set up, and I thought that would be more valuable for assessing #27 and #29)

I don't see any observations related to #27 and #29.  And #28 was also a priority (per https://github.com/phetsims/equality-explorer/issues/28#issuecomment-355651129).  Any observations related to those issues?

General conclusions?

**Comment by pixelzoom** [comment]
Observations related to #27, #28, #29 were added to those issue.

**Comment by amanda-phet** [comment]
I think we can close this issue since interviews are complete, observations were summarized here and in the design doc and shared with the team.
