### ISSUE TITLE
implement challenge engine

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#38]
Challenge generation for the "Solve It!" (game) screen is described in it's own design document. See https://docs.google.com/document/d/1vG5U9HhcqVGMvmGGXry28PLqlNWj25lStDP2vSWgUOo/edit.  

It may be possible to structure this as a self-contained module that I could spin off to another developer. In 2/9/18 Slack conversation, @ariel-phet and I discussed the possibility of having @andrea-phet work on this.

See also https://github.com/phetsims/equality-explorer/issues/34 for a more complete specification of the "Solve It!" screen.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/equality-explorer/issues/45 proposes adding support for variable terms to the universal operation control. The main motivation is to make it possible to have challenges with variables on both sides of the equations.  And that will require revising the specification for levels and challenges.  So implementation of the challenge engine is on hold pending resolution of #45.

**Comment by pixelzoom** [comment]
It sounds like we're proceeding with support for variable terms in the universal operation.  So we'll be able to have challenges with variables on both sides of the equation.  Assigning to @amanda-phet to revise the specification for generating challenges.

**Comment by amanda-phet** [comment]
Level 4 challenge generation specification is complete.

**Comment by pixelzoom** [comment]
The challenge engine is implemented. Challenges are not yet being displayed, but if you run with `?showAnswers`, you'll see debug information about the challenge and its derivation below the Snapshots according box. For example:

![screenshot_74](https://user-images.githubusercontent.com/3046552/38963649-3a4f56e0-4330-11e8-966a-ad050efa4eef.png)

**Comment by pixelzoom** [comment]
With `?showAnswers`, a "test challenge generators" button appears at the bottom of the level-selection UI.  Pressing this button generates 100 challenges for each level, and verifies that they meet the requirements in the design document.   Output is to the browser console.

![screenshot_563](https://user-images.githubusercontent.com/3046552/38884994-9fb7ea68-422e-11e8-9e23-324c9c51449f.png)

**Comment by pixelzoom** [comment]
Many refinements to challenge design doc via Slack today, with @amanda-phet.

**Comment by pixelzoom** [comment]
@amanda-phet please review [1.0.0-dev.95](https://bayes.colorado.edu/dev/html/equality-explorer/1.0.0-dev.95/phet/equality-explorer_en_phet.html) to verify that challenge generation matches the specification.  Let me know if any further tweaks are needed.  Highly recommended to run with `?showAnswers` to display the debugging output that displays the challenge type and derived values -- see  https://github.com/phetsims/equality-explorer/issues/38#issuecomment-381785898.

Relatively high priority, since it will be easiest to make changes while this is still fresh in my mind.

**Comment by pixelzoom** [comment]
In a phone call, @amanda-phet indicated that she might want to make some tweaks to the challenge generation specification.  Let me know what you'd like to change.

**Comment by amanda-phet** [comment]
My issue with with level 3 type 1. A problem like this, for instance, could be solved (and I would encourage students to solve) by first multiplying the entire equation by 5 to remove any fractions. It is much simpler math than adding 9 to both sides first (although, the computer will do that computation for you!). If you multiply by 5, you end up with 4x-45=67. The next step is to add 45 to both sides, which is done in 5 steps because our picker only goes to 10. 

<img width="1271" alt="screen shot 2018-04-25 at 1 31 45 pm" src="https://user-images.githubusercontent.com/7852916/39274994-ebef0182-48a0-11e8-9af0-4538ef6aec8c.png">

I think the only option right now would be to restrict b (in this challenge type) to a smaller range. Even [-3,3] would be an improvement, because while we could end up with an equation similar to the above, the largest number we'd need to add to both sides is 30, which can be done in 3 steps, and that is better than 5.

@pixelzoom any other thoughts for restricting the product b•d?

**Comment by pixelzoom** [comment]
The current specification for Level 3, type 1 is:

> Form: (a/d)x + b = c
Let x be a random integer between [-40,40], x !== 0
Let d be a random integer between [-10, 10], d !== [0,1,-1]
Let a be a random integer between [-10,10], a % d !== 0
Let b be a random integer between [-10,10], b !== 0
Let c = (a/d)x + b, c == 0 is OK

With that specification, I don't see any other way to constraint things other than what you suggested (limiting the range of `b`).

Have you investigated other ways to specify this, like deriving a value other than `c` ?

**Comment by pixelzoom** [comment]
4/26/18 design meeting:

With b=[-3,3], b*d will be [-30,30].  I'll implement that change, and @amanda-phet can play around with it to see if the challenges are still interesting enough.

**Comment by pixelzoom** [comment]
4/26/18 design meeting:

A challenge in Level 4 that @DianaTavares found that is problematic, see below. @amanda-phet will investigate the generation.  

Need to reject anything where `|a - m| > 10` and odd, which is impossible.  After choosing `a`, limit range of `m` based on `a`.  @amanda-phet will come up with the function of `a` that computes range of `m`.

![screenshot_596](https://user-images.githubusercontent.com/3046552/39328697-61825ee0-4959-11e8-80fb-3eadf5165393.png)

**Comment by amanda-phet** [comment]
generate *a*, a random integer from [-10,10] *a*≠0. 
then *m* =  a random integer from [*a*-10, *a*+10], excluding 0 and *a*.

**Comment by amanda-phet** [comment]
I've updated the google doc with these two changes (level 3 type 1, and level 4).

**Comment by pixelzoom** [comment]
@amanda-phet @DianaTavares I've made the changes for Level 3 (type 1) and Level 4.  Please verify in this dev version:

https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.102/phet/equality-explorer_en_phet.html?showAnswers

Note the `?showAnswers` query parameter.  If there's a problem, I'll need a screenshot that shows the derivations, which is what this query parameter provides.  Thanks!

**Comment by amanda-phet** [comment]
The challenges are all looking really good to me. I've spent quite a bit of time refreshing on all 4 levels now and don't see any issues. I realize that level 3 may present some challenges that need multiple steps to add/subtract a constant but I think the limit we put on those is acceptable).

**Comment by pixelzoom** [comment]
@DianaTavares do you want to take this for a test drive before I close this issue?

**Comment by DianaTavares** [comment]
I just see it, the problem with the division is solved!

**Comment by DianaTavares** [comment]
But I still having questions about some exercises with big constants, for example this one:
![screen shot 2018-04-27 at 11 50 05 am](https://user-images.githubusercontent.com/26031501/39377106-3e0f8862-4a11-11e8-8fa2-43f098c51138.png)

at the beginning the exercise was  17x + 142 = 7x - 8, my first step was take away the 7x (because the 17x require 2 steps). But now I have the problem of take away 142. 

I see in the interview that if the student see that need a operation with big numbers, she/he prefers refresh the exercise. Even when they know what to do.

**Comment by pixelzoom** [comment]
@amanda-phet can you discuss "big constants" (see above) with @DianaTavares?

**Comment by amanda-phet** [comment]
I found something similar... 

I have two ideas. 

1. Make x a smaller range. However it's possible for n to still be as big as 110 even if x is restricted to [-10,10], so that doesn't seem like much of a solution. 

2. Change the generation slightly so that a and m are no more than 10 apart, AND are within [-10,10]. Currently, m = [a-10, a+10]. If a=10, m could be as large as 20. instead, it would be preferable to restrict m  further so that m is between [a-10, a+10] AND |m|≤10. Yesterday I only made sure |a-m|≤10. 

Chris, what is the best way to specify this? Here is an illustration of what is in my head :) 

![image](https://user-images.githubusercontent.com/7852916/39379950-1b8e4be4-4a1a-11e8-9dc5-b0ee37776cb8.png)

**Comment by pixelzoom** [comment]
@amanda-phet @DianaTavares I revised the constraints for Level 4 'm' in this dev version:
https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.106/phet/equality-explorer_en_phet.html?showAnswers

From the design doc:
> Let m be a random integer between [-10, 10], m ≠ 0, m ≠ a, |a-m|≤10

Better?

**Comment by DianaTavares** [comment]
I think is perfect!  I try several times and I found all the exercises according with the sim level. Thanks @amanda-phet and @pixelzoom!

**Comment by pixelzoom** [comment]
@amanda-phet if everything looks OK, please close this issue.

**Comment by amanda-phet** [comment]
Level 4 is looking great to me as well. I really like seeing the large constants, too. It's a good experience for students to have. 

Since all of the levels are good I think we can close this issue.
