### ISSUE TITLE
Terms can be left stranded at the end or their animations

### ISSUE THREAD

**Issue by phet-steele** [phetsims/equality-explorer#41]
1. Stack two terms onto one side of a scale.
2. Quickly "double click" the bottom term. Place your cursor towards the bottom center of this term to make it easier.

The idea behind the double click is that you are moving the fallen term on the second click before the first term reaches the end of its animation back up. This leaves the top term (previously the bottom term) stranded with nothing below it.

![eqex01](https://user-images.githubusercontent.com/5863899/36925339-b9223c1a-1e2f-11e8-9e2e-a534f49c2f1a.gif)

Seen on macOS 10.13.3 Chrome. For #40. This has existed since the beginning of this sim's life (maybe a hyperbole), not new since dev.63.

<details>
<summary>Troubleshooting Information</summary>

URL: https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.64/phet/equality-explorer_en_phet.html
Version: 1.0.0-dev.64 2018-03-02 20:54:47 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"43c79e6e","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"37c07d8c","branch":"master"},"dot":{"sha":"8d471f40","branch":"master"},"equality-explorer":{"sha":"5d6becd0","branch":"master"},"joist":{"sha":"39c8d96a","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"phet-core":{"sha":"f35ff65e","branch":"master"},"phet-io":{"sha":"a0f741c0","branch":"master"},"phet-io-website":{"sha":"28284828","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"c84e3046","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"ebf7c7dc","branch":"master"},"phet-io-wrapper-sonification":{"sha":"e68394e5","branch":"master"},"phet-io-wrappers":{"sha":"eddb93a4","branch":"master"},"phetcommon":{"sha":"a5a7478c","branch":"master"},"query-string-machine":{"sha":"485e174e","branch":"master"},"scenery":{"sha":"316b20e3","branch":"master"},"scenery-phet":{"sha":"46c86efd","branch":"master"},"sherpa":{"sha":"9c6ec322","branch":"master"},"sun":{"sha":"1f8ecfe4","branch":"master"},"tandem":{"sha":"7f499d9e","branch":"master"},"twixt":{"sha":"3f2cc19d","branch":"master"}}
</details>

**Comment by pixelzoom** [comment]
Reproduced.  The bottom term is not really being double-clicked.  It's easier to see what's going on if you use 2 terms with different types, for example:

![screenshot_500](https://user-images.githubusercontent.com/3046552/36988164-655ed92a-205b-11e8-90da-297dc1bbb84f.png)

The first click removes the square from the grid, and sphere immediately moves down.  The second click then selects the sphere, removing it from the grid.  And the bug is that the square doesn't get moved down in that case. 

![screenshot_501](https://user-images.githubusercontent.com/3046552/36988315-d4149454-205b-11e8-863b-5a5bd0327609.png)

The problem is undoubtedly in TermDragListener.

**Comment by pixelzoom** [comment]
There a general deficiency in TermDragListener.  When a term is released, a target cell in the grid is identified, and the term animates to that cell.  In the meantime, a cell _below_ the target cell may become empty. 

Here's another scenario that doesn't involve double clicking.  Run with `?showGrid&speed=0.25` to show the grid and slow the animation.  Start with a square on the scale:

![screenshot_502](https://user-images.githubusercontent.com/3046552/36989623-73fb6800-205f-11e8-925c-724e88d736d9.png)

Drag a sphere directly above the square, and release it.  The target cell will be the one directly above the square, and the sphere will start animating towards that cell. 

![screenshot_505](https://user-images.githubusercontent.com/3046552/36989696-acb51ed4-205f-11e8-9857-4de7281efe1e.png)

Before the sphere reaches the cell above the square, grab the square and move it out of the way.  The sphere will stop at the target cell, and things will look like this:

![screenshot_506](https://user-images.githubusercontent.com/3046552/36989801-09b5b59e-2060-11e8-82a4-7407b7f97c91.png)

Two ways to resolve this:

(1) On every time-step, determine whether the current target cell is appropriate. If not, choose a more appropriate target cell and resume animation towards that cell.   This is a non-trivial computation, and would negatively impact responsiveness. So while this is the most "physically correct" option, it's not really practical.

(2) When a term reaches the target cell, check if any cells below it are empty.  If they are, immediately shift term(s) down to compact the column.  This is similar to what we do when a term is removed from the bottom of the stack. The same algorithm could be reused, which has no adverse performance affects. 

Since this is a bit of an atypical use case, I'm going with (2).

**Comment by pixelzoom** [comment]
Fixed in [1.0.0-dev.65](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.65/phet/equality-explorer_en_phet.html).  When a term is added to (or removed from) the grid, the associated column is compacted if it contains holes. 

@phet-steele please verify.

**Comment by phet-steele** [comment]
Works for me, thanks.
