### ISSUE TITLE
iOS: equation does not scale to fit in accordion box

### ISSUE THREAD

**Issue by phet-steele** [phetsims/equality-explorer#57]
Text doesn't scale down properly with long strings (in the equality panel):

![img_0153](https://user-images.githubusercontent.com/5863899/38215678-d796d7fa-3685-11e8-8f89-f2727332c62a.PNG)

The same strings look fine on my macOS 10.13.3 Chrome.

Seen on iPad Air 2 iOS 11.2.5. For #53.

**Comment by pixelzoom** [comment]
No idea why this would behave differently on iOS.

Scaling of the equation in the accordion box is a bit more complicated than normal, because the relational operator needs to remain centered over the scale.   Here's the relevant code, EquationAccordionBox.js line 67, where "side" refers to a "side" of the equation.

```js
    var equationNode = new EquationNode( leftTermCreators, rightTermCreators );

    // wrapper to avoid exceeding stack size when bounds of equationNode changes
    var equationParent = new Node( { children: [ equationNode ] } );

    equationNode.on( 'bounds', function() {

      // Compute the scale required to keep the equation inside the accordion box, and centered on
      // the relational operator. This is more complicated than setting maxWidth because the equation's
      // relation operator is centered in the accordion box, and only one side of the equation may get
      // too wide. equation.x is the center of the equation's relational operator.
      var maxSideWidth = contentWidth / 2;
      var leftSideOverflow = Math.max( 0, equationNode.x - equationNode.left - maxSideWidth );
      var rightSideOverflow = Math.max( 0, equationNode.right - equationNode.x - maxSideWidth );
      var maxOverflow = Math.max( leftSideOverflow, rightSideOverflow );

      // Scale and center the parent
      equationParent.setScaleMagnitude( maxSideWidth / ( maxSideWidth + maxOverflow ) );
      equationParent.x = invisibleRectangle.centerX;
      equationParent.centerY = invisibleRectangle.centerY;
    } );
```

(Edited to reflect https://github.com/phetsims/equality-explorer/commit/791d0a994749d93ac2bbbd1f0b016c487864809b.)

**Comment by pixelzoom** [comment]
I also see from the screenshot in https://github.com/phetsims/equality-explorer/issues/57#issue-310608713 that the relational operator is not remaining centered.

@phet-steele I don't have an iPad handy.  Does the equation scale at all on iOS?  Or does it just keep getting wider as the numbers get bigger?

**Comment by pixelzoom** [comment]
I'm going to remove the "type:i18n" label, since this is not specific to i18n.  Regardless of what makes the equation big, it should be scale to fix inside the accordion box, and its relational operator should remain centered.

**Comment by phet-steele** [comment]
> Does the equation scale at all on iOS? Or does it just keep getting wider as the numbers get bigger?

@pixelzoom it does scale. What you are seeing is the extent of the horizontal scaling. Here is a gif of it happening:

![eqex04](https://user-images.githubusercontent.com/5863899/38268339-1362cb80-373b-11e8-8c39-9ed84a5a3c32.gif)

**Comment by pixelzoom** [comment]
@jjohnson5253 Any idea why the code in https://github.com/phetsims/equality-explorer/issues/57#issuecomment-378320706 would behave differently on iOS?

**Comment by pixelzoom** [comment]
@jonathanolson  Any idea why the code in https://github.com/phetsims/equality-explorer/issues/57#issuecomment-378320706 would behave differently on iOS?

**Comment by jjohnson5253** [comment]
@pixelzoom What part of the code resizes the accordion box when the equation gets bigger? As in, where is `equationNode.on( 'bounds', function()` called to resize the box?

**Comment by pixelzoom** [comment]
@jjohnson5253 You can ignore this, I meant to assigning to @jonathanolson.

But to answer your question (in case you're curious), `equationParent.setScaleMagnitude` scales the equation, because `equation` is a child of `equationParent`.  If I scaled `equation` directly, I'd get caught in an infinite loop, since that would then call the `equation.on( 'bounds',...)` callback.

**Comment by jonathanolson** [comment]
I'm curious if it can be reproduced on desktop Safari? There's a chance things are erroring out.

I'm not immediately sure what's going on. There's a chance that the x-set and scale-set interaction is mainly acting buggy on iOS due to sizes.

Instead of grabbing the `equationNode.x` in the computations (which may be somewhat affected by scale changes), can `equationNode.x - equationNode.left` be replaced with `-equationNode.localBounds.left` and `equationNode.right - equationNode.x` with `equationNode.localBounds.right`?

**Comment by jonathanolson** [comment]
Found we're able to reproduce the bug on any platform by increasing the integerFontSize to (e.g.) 50.

**Comment by jonathanolson** [comment]
So it looks like (on my side) the code snip above is working as intended.

The contentWidth (on my test) is 581. The equationParent's width does NOT go above 581. However, the entire width of the accordion box's background is 513 (smaller). So I presume the issue is with the logic deciding what the contentWidth is.

**Comment by pixelzoom** [comment]
@jonathanolson said:
> ... So I presume the issue is with the logic deciding what the contentWidth is.

Please elaborate, I don't understand  what the conclusion is.

**Comment by jonathanolson** [comment]
Your contentWidth is larger than the accordion box's width (at least before it has overflowing content). Unless you want to explicitly allow the overflow, you want to have the content be smaller than the containing accordion box.

Is it actually valid for the contentWidth (the variable in the code snippet used to compute maxSideWidth ) actually meant to be larger than the accordion box? If so, I don't understand what the issue is, and if not, it seems that the bug is triggered by the contentWidth being larger than desired (and thus the bug would not be in your code snippet above).

**Comment by pixelzoom** [comment]
@jonathanolson said:
> Your contentWidth is larger than the accordion box's width ...

I don't follow. `contentWidth` is a constant that _determines_ the accordion box's width.

Putting a `debugger` statement at the end of EquationAccordionBox's constructor, I see:

```
> contentWidth
581
> options.contentXMargin
20
> contentWidth + ( 2 * options.contentXMargin )
621
> 
this.width
621
```

So the accordion box width is exactly as I would expect.  Please clarify.

**Comment by pixelzoom** [comment]
To make sure there wasn't something peculiar with one of the EquationAccordionBox instances, I put this statement at the end of its constructor:

`console.log( 'contentWidth=' + contentWidth + ', contentXMargin=' + options.contentXMargin + ', this.width=' + this.width );`

I see the same output for the EquationAccordionBox in each of the 4 screens:

> contentWidth=581, contentXMargin=20, this.width=621

**Comment by pixelzoom** [comment]
Discussed with @jonathanolson via Zoom. The problem is caused by different font size on iOS, and the fact `invisibleRectangle` gets scaled by this bit of code:

```js
    var contentNode = new Node( {
      children: [ invisibleRectangle, equationParent ],
      maxWidth: contentWidth,
      maxHeight: contentHeight
    } );
```

No scaling should be done to `invisibleRectangle`.

**Comment by pixelzoom** [comment]
Fixed in above commit.  

@phet-steele please verify in [1.0.0-dev.88](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.88/phet/equality-explorer_en_phet.html).

**Comment by pixelzoom** [comment]
You may notice some `console.log` output in 1.0.0-dev.88.  You can ignore it, it was been removed in a later commit.

**Comment by phet-steele** [comment]
Looks good on iOS, and other browsers when manually adjusting the font size.
