### ISSUE TITLE
Reward dialog appears independent of active screen

### ISSUE THREAD

**Issue by phet-steele** [phetsims/equality-explorer#84]
1. Solve It! screen, on the last challenge before receiving a reward....
2. Set up the correct operation where pressing "Go" would result in the answer and give you the reward (in other words, you are one step away from winning)
3. Press "Go" and BEFORE the operation can be applied (while there is still animation), switch screens OR press the back button in the score bar OR go to the home screen.

The reward dialog will still appear wherever you are. Here is it appearing on the home screen:

<img width="1396" alt="screen shot 2018-05-01 at 10 28 02 am" src="https://user-images.githubusercontent.com/5863899/39481924-5cea8c02-4d2a-11e8-818d-a7d5bc45a72c.png">

@pixelzoom this does not appear to have any buggy effects on the sim, other than not being able to see the reward node 😢. Clicking either button or dismissing the dialog in general appears to be safe.

Seen on macOS 10.13.4 Chrome. For #76.

<details>
<summary>Troubleshooting Information</summary>

URL: https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.108/phet/equality-explorer_en_phet.html?log&showAnswers&rewardScore=1
Version: 1.0.0-dev.108 2018-05-01 00:21:19 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
Language: en-US
Window: 1396x1013
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4ce9d171","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"1ee8228c","branch":"master"},"dot":{"sha":"14cc3d15","branch":"master"},"equality-explorer":{"sha":"1cd3b2bd","branch":"master"},"joist":{"sha":"7874f857","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"phet-core":{"sha":"752ea737","branch":"master"},"phet-io":{"sha":"45e5b058","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"dfc83c89","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"020f3ed6","branch":"master"},"phet-io-wrappers":{"sha":"a00f4c29","branch":"master"},"phetcommon":{"sha":"9a8756e6","branch":"master"},"query-string-machine":{"sha":"f9def230","branch":"master"},"scenery":{"sha":"e01f08e7","branch":"master"},"scenery-phet":{"sha":"2c1ff10e","branch":"master"},"sherpa":{"sha":"abef4445","branch":"master"},"sun":{"sha":"09efcff9","branch":"master"},"tandem":{"sha":"718d8a58","branch":"master"},"twixt":{"sha":"bed340f2","branch":"master"},"vegas":{"sha":"b30d7150","branch":"master"},"vibe":{"sha":"f2175b9b","branch":"master"}}
</details>

**Comment by pixelzoom** [comment]
Hmmm... This is not good, because it indicates a general problem with dialogs.

**Comment by pixelzoom** [comment]
There are multiple general problems here:

• The operation animation uses TWEEN. There is no way to associate a TWEEN animation with a screen, and all TWEENS are treated as global by joist.  So when we switch screens, the TWEEN animation continues to run, and displays the dialog when the operation is applied.

• There is no way to associate a dialog with a screen. All dialogs are treated as global by joist.  So when the TWEEN animation completes and tells joist to display the dialog, joist displays it on whichever screen is currently active (the home screen, in the example provided by @phet-steele).

So the options here are:

(1) Live with it.
(2) Reimplement all TWEEN animations using "something else".  Since TWIXT.Animation is _still_ not ready, this probably means rolling my own animation. This would take a day or two.
(3) Reimplement joist Dialog to be screen specific. This would be a big project, and is not really an option right now.

**Comment by pixelzoom** [comment]
Assigning to @amanda-phet to choose an option.  

Mentioning @ariel-phet too, in case he wants to weigh in.  FYI, the root cause of this problem is that `TWIXT/Animation` (the eventual replacement for TWEEN) is still not done.  In the future, I'm going to roll my own sim-specific animations until something in common code is actually completed.  For this specific issue, we can either live with the problem, or push the schedule out a week.

**Comment by pixelzoom** [comment]
After discussion on Slack developer channel...  I chose option (2).  I rewrote the animation using TWIXT/Animation, because @jonathanolson said that it "doesn’t have a lot of the desired hooks yet, and there are improvements, but I still think it is ready for general use. And I will update any usages whenever I make breaking changes."   

The conversion was not exactly straightforward, but now that I've negotiated the landmines, I may convert the other TWEEN animations in this sim.

@phet-steele please test in master.

**Comment by amanda-phet** [comment]
I was going to say option (1), but I'm glad it is working out ok to use TWIXT.

**Comment by phet-steele** [comment]
@pixelzoom your conversion works except for the middle case in step 3:

> switch screens OR press the back button in the score bar OR go to the home screen.

The "press the back button in the score bar" will still have the dialog appear in the level select.

**Comment by pixelzoom** [comment]
The remaining problem is due to the fact that the level-selection UI is part of the same `ScreenView`.  So after pressing the back button, the operation animations continue to run, and display the dialog when they complete.

Discussed with @phet-steele on Slack and we agreed that it makes sense to cancel in-progress operation animations when the back button is pressed.  Implemented in the above commit. 

@phet-steele please review in master.

**Comment by phet-steele** [comment]
Working 👍
