### ISSUE TITLE
warning: AudioContext was not allowed to start

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#98]
Related to general vibe issue https://github.com/phetsims/vibe/issues/32.

This warning started appearing in the browser console about a week ago, and occurs 100% of the time in requirejs mode (not tested in built versions)

> Sound.js?bust=1525639065867:27 The AudioContext was not allowed to start. It must be resume (or created) after a user gesture on the page. https://goo.gl/7K7WLu

According to @jbphet, this can prevent audio from playing.  And nothing sim-specific can be done to address this. So https://github.com/phetsims/vibe/issues/32 needs to be addressed  before this sim can be published.

**Comment by pixelzoom** [comment]
@amanda-phet @ariel-phet FYI.

**Comment by jbphet** [comment]
@pixelzoom - can you please provide OS and browser info to make this easier for me to duplicate?

**Comment by pixelzoom** [comment]
As reported in vibe issue https://github.com/phetsims/vibe/issues/32#issuecomment-386911406:

> Chrome 66.0.3359.139 on macOS 10.11.6

**Comment by jbphet** [comment]
After much mucking about with flags, Media Engagement Indices, and such, I found that I am able to duplicate this reliably using the MacBook Pro generally referred to a "Arnab's dev machine" on Chrome 66.0.3359.139, Mac OS 10.13.4, but only in incognito mode.  So far, I haven't been able to make it happen at all on my Windows 10 machine, which is running Chrome version 66.0.3359.170 (Official Build) (64-bit).  Since the Windows version is a higher number, it made me wonder if it is a more recent version where they have adjusted the policy.  There are certainly a fair number of people complaining about this change in various forums on line.  To test this out, I installed the latest Chrome Canary version, which is 68.0.3430.0, on the aforementioned Mac.  I was not able to duplicate the problem of the disallowed audio context on this version.

@pixelzoom - can you try this, i.e. testing with the latest Chrome Canary and seeing if the problem goes away?

**Comment by pixelzoom** [comment]
I don't see the warning in Chrome Canary `68.0.3430.0 (Official Build) canary (64-bit)`.  I tested with and without Incognito.

**Comment by jbphet** [comment]
My educated guess is this: They modified Chrome such that it allows the creation of the audio context, but doesn't allow any usage of it until the user has interacted with the page.  That would prevent auto-play of videos, which is what they were trying to do, without messing up PhET and everyone else who makes apps that include audio.

I'm not sure what the release schedule looks like for Equality Explorer, so I'm going to assign this to @ariel-phet to decide whether we should wait until the first RC is ready and see if the problem exists on the latest version of Chrome or go ahead with trying to implement a workaround.  My own preference would be to defer and wait until we know whether this is a problem at RC time, since that would save me the time of implementing and testing a fix.  The downside of waiting is that if it **is** a problem at that time, the workaround will have to be done on a branch and all that, so it will be a somewhat more complicated problem.  Maybe we could assess the situation just before doing the RC branch and implement a fix then if needed (assuming we remember).

**Comment by pixelzoom** [comment]
Current milestones for Equality Explorer are at [this link](https://docs.google.com/document/d/1xu9nawWcndFqgg5zyCGm25h-OFUsuFYnXF3QHW42spQ/edit#heading=h.zfo7jfd6g7pk).  8/1 publication date is effectively 7/18, since it does not account for my vacation.  To meet that, we should start RC by 6/18.

**Comment by pixelzoom** [comment]
If we're relying on the fix in Canary 68, that's not going to work with the Equality Explorer milestones.  According to the [Chrome release schedule](https://www.chromestatus.com/features/schedule), Chrome 68 is anticipated to be stable (GA) on July 23, about 1 month after Equality Explorer needs to start RC testing.

**Comment by pixelzoom** [comment]
@jbphet Have you tried Chrome 67, which will be stable on May 28?

**Comment by ariel-phet** [comment]
@pixelzoom this warning appears in the console...is there any other issue (besides audio not working in the sim)? I do not necessarily see that as a "blocking issue" if it is will be fixed in the browser at some point in the nearish future. Especially since this sim is unlikely to get much usage until after August, I would be fine on punting on this, and putting a reminder on the calendar for us to check into the issue after chrome 68 (or 67) if it is not crashing the sim or such.

**Comment by pixelzoom** [comment]
I would have thought that audio not working would be considered a serious issue, especially in a sim with a game.  But if you don't consider that I problem, then I'll mark this as deferred and ignore it for the purposes of 1.0 release.

**Comment by pixelzoom** [comment]
@ariel-phet In https://github.com/phetsims/vibe/issues/32#issuecomment-391470509, @jbphet indicated that this issue is going to resurface when Chrome 70 is published in October 2018, and that developers have been granted a temporary reprieve in which to address it.   With that new information... Do you want this issue to be addressed before Equality Explorer 1.0 is published, or are you comfortable with having to republish before Chrome 70 hits?

**Comment by ariel-phet** [comment]
@pixelzoom lets plan on trying to address it before publication. If @jbphet has not come up with a robust workaround by the time you are ready to branch for RC, lets discuss further.

**Comment by pixelzoom** [comment]
Removing deferred label. @jbphet FYI.

**Comment by pixelzoom** [comment]
@jbphet FYI, RC testing is schedule to begin no later than 7/11/18.

**Comment by pixelzoom** [comment]
Work in https://github.com/phetsims/vibe/issues/32 appears to have addressed this.  There's no warning in Chrome 66 console (macOS), and audio works in the _Solve It!_  screen.  

Closing.
